# Generated by Django 5.0.1 on 2024-04-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_quiz_category'),
        ('teams', '0002_alter_team_created_by'),
        ('teams_in_quizzes', '0003_alter_teaminquiz_quiz_alter_teaminquiz_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='teaminquiz',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
