# Generated by Django 5.0.1 on 2024-04-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_category'),
        ('questions_in_quizzes', '0001_initial'),
        ('quizzes', '0006_quiz_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninquiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='questioninquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.quiz'),
        ),
    ]
