# Generated by Django 5.0.1 on 2024-04-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_category'),
        ('questions_in_quizzes', '0002_alter_questioninquiz_question_and_more'),
        ('quizzes', '0007_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninquiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
        migrations.AlterField(
            model_name='questioninquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
        ),
    ]
