# Generated by Django 5.0.1 on 2024-02-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_list_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='list_of_questions',
        ),
    ]
