# Generated by Django 5.0.1 on 2024-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quiz_list_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='team_limit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
